spring.application.name=ms-gateway
server.port=8091

spring.main.web-application-type=reactive
spring.autoconfigure.exclude=org.springframework.cloud.gateway.server.mvc.GatewayServerMvcAutoConfiguration

eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=ms-clientes
spring.cloud.gateway.server.webflux.routes[0].uri=lb://MS-CLIENTES
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/clientes/**,/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-museos
spring.cloud.gateway.server.webflux.routes[1].uri=lb://MS-MUSEOS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/museos/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-reservas
spring.cloud.gateway.server.webflux.routes[2].uri=lb://MS-RESERVAS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/reservas/**

spring.cloud.gateway.server.webflux.routes[3].id=ms-pagos
spring.cloud.gateway.server.webflux.routes[3].uri=lb://MS-PAGOS
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webflux.routes[4].id=ms-notificaciones
spring.cloud.gateway.server.webflux.routes[4].uri=lb://MS-NOTIFICACIONES
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.server.webflux.routes[5].id=ms-eventos
spring.cloud.gateway.server.webflux.routes[5].uri=lb://MS-EVENTOS
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/eventos/**

spring.cloud.gateway.server.webflux.routes[6].id=ms-exposiciones
spring.cloud.gateway.server.webflux.routes[6].uri=lb://MS-EXPOSICIONES
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/exposiciones/**

spring.cloud.gateway.server.webflux.routes[7].id=ms-tickets
spring.cloud.gateway.server.webflux.routes[7].uri=lb://MS-TICKETS
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/tickets/**

spring.cloud.gateway.server.webflux.routes[8].id=ms-empleados
spring.cloud.gateway.server.webflux.routes[8].uri=lb://MS-EMPLEADOS
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/empleados/**

spring.cloud.gateway.server.webflux.routes[9].id=ms-salas
spring.cloud.gateway.server.webflux.routes[9].uri=lb://MS-SALAS
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/salas/**